### ISSUE TITLE
Compressing images on upload

### ISSUE THREAD

**Issue by smelamud** [MoeraOrg/moera-issues#177]
Add options for (re-)compressing images on upload to save disk space and traffic. Possible options are:

1. Lowering resolution.
2. Increasing JPEG compression ratio.
3. Converting to WebP (not supported by IE and Safari (before macOS 11 Big Sur)).

It is desirable to have different compression options for images of different purpose. Such as:

1. Images in posts.
2. Image previews
3. Images in comments.

**Comment by tigra** [comment]
SeeweedFS is very fast and economic storage for lots of small files (better then storing'em in e.g. ext4 filesystem). 
https://github.com/chrislusf/seaweedfs

It also allows resizing images out of box:
http://localhost:8080/3/01637037d6.jpg?height=200&width=200

(still will need to compress/resize very big image to the maximal size needed, to save disk space, for the rest, this mechanism can be relied upon)

Worked very well for hundreds of thousands of images for e-commerce aggregator.
However not sure if this is not an overkill for a small node.

**Comment by smelamud** [comment]
Not all nodes will be small. If it is possible to create pluggable support of this thing, it will be very useful.

**Comment by smelamud** [comment]
Moera architecture requires that posts with images should be signed with author's key before sending to the target node. Therefore, the target node cannot modify the image, otherwise the signature will be broken. So, in the current implementation, the target node tells the author what are the requirements for uploaded images are and may reject the images that don't fulfill them. The image compression itself is performed on the client/source node side.
