### ISSUE TITLE
Opening dropdown menu clears selection on the page

### ISSUE THREAD

**Issue by smelamud** [MoeraOrg/moera-issues#277]
Need to preserve selection on the page when opening a dropdown menu. This is needed, for example, when user selects some text in a post and then wants to select "Reply..." from the post menu.

**Comment by eliduvid** [comment]
Couple of hours of fiddling and I have the answer: just making menu button actual `button` (and not `div`) should do the trick .
https://jsfiddle.net/cu2sojnw/10 - empirical evidence.

**Comment by smelamud** [comment]
Thanks a lot!
