### ISSUE TITLE
Change post date/time allows to enter any text

### ISSUE THREAD

**Issue by MalkaNessy** [MoeraOrg/moera-issues#283]
Time and date of the post. If you carefully change the date or time, and press enter, everything is fine. 

But if you start to enter any text in this field, it is entered, and if after that you press enter or just click on an empty space on the screen, the whole page is completely empty (as if trying to reload, but cannot). 
If you reload the page from the browser, it opens in the same position (before attempting to enter extraneous text)

**Comment by smelamud** [comment]
Fixed.
