### ISSUE TITLE
Can't change name back

### ISSUE THREAD

**Issue by almaron** [MoeraOrg/moera-issues#304]
I wanted to register a second blog so I went to my profile and clicked "Register another". Instead of registering a new blog it changed the name in the current as well as blocking the ability to edit old posts and showing a small "0" next to the name in the old ones. 

Any attempt to update the name or transfer it get denied with both the old word combination and the new one I got when registering the new name. 
How do I get my handle back?

**Comment by smelamud** [comment]
You need to go to your Profile page and click "Transfer Name". Then enter your old name and keywords for it.

**Comment by almaron** [comment]
@smelamud I have. It sais signature check failed though I'm absolutely positive the words are correct (I have both a screenshot and a text file that I copied the words to).

**Comment by almaron** [comment]
![image](https://user-images.githubusercontent.com/674925/105134803-04960400-5b00-11eb-8311-c2b654309551.png)

**Comment by smelamud** [comment]
This sounds very strange. I just verified again the whole sequence: create the first name, register another, transfer the first name back - everything works as expected.

Please, recheck that you enter correct words (that correspond to the name you want to set) in correct order (each word has a number).

You may ping me on my Telegram https://t.me/smelamud and we'll try together to figure out what is happening.

**Comment by almaron** [comment]
Did a couple more tries from another computer and it worked on the last one. Guess problem solved.
