### ISSUE TITLE
Hide the generation number in the UI

### ISSUE THREAD

**Issue by almaron** [MoeraOrg/moera-issues#305]
Showing the generation number next to the username in all posts and comments looks ugly, confusing and unnecessary.
![image](https://user-images.githubusercontent.com/674925/105157273-dcb59900-5b1d-11eb-9436-39addf648100.png)
![image](https://user-images.githubusercontent.com/674925/105157345-f060ff80-5b1d-11eb-8fe1-4ca250c407ba.png)

**Comment by smelamud** [comment]
Done.
