### ISSUE TITLE
Open links to Moera posts in the client

### ISSUE THREAD

**Issue by grep0** [MoeraOrg/moera-issues#317]
When a user clicks in mobile client on a url pointing to a Moera post, they should stay in the client instead of getting to the web browser.

![screenshot](https://i.ibb.co/PGQ4vFZ/Screenshot-20210318-163824.png)

**Comment by smelamud** [comment]
To achieve that, we need to distinguish between links to Moera nodes and links to any other site. This is possible after fetching response headers and checking whether they contain `X-Moera` header.

We can do this on client side, but it will add a delay between clicking on a link and loading the page. There are optimizations (like prefetching) that may make this slightly faster.

Doing this on backend is much better. The backend may fetch the links, check the header and set `data-nodename` and `data-href` attributes of `<a>`. They are already supported by the client. More than that, if the target node is moved and the name is pointed to a different URL, `data-nodename` and `data-href` will assist to find a correct URL.

On the downside, analyzing links cannot be done synchronously, so when a post is added we need to add it as is, without analyzing. After that some postprocessor will need to analyze the links and update the post, if needed. So it is not as easy as it sounds, but definitely needs to be done.

**Comment by smelamud** [comment]
The first approach (fetching a link and checking `X-Moera` header) is implemented. But the second one is better and we have plans implementing it, so leaving this issue open.

**Comment by smelamud** [comment]
Recent Moera releases contain implementation of universal Moera links that use redirector (`moera.page`). This makes detection of Moera links trivial.
