### ISSUE TITLE
Run client against a remote server

### ISSUE THREAD

**Issue by grep0** [MoeraOrg/moera-issues#322]
According to [client readme](https://github.com/MoeraOrg/moera-client-react#readme) you are expected to run a client against a local server. For development/debugging purposes, is it possible to connect a dev client to the existing remote node?

**Comment by smelamud** [comment]
The only problem with this is that modern browsers deny loading content from HTTP sites for HTTPS sites. So, if you find a way to serve a dev client with HTTPS, it should work. I've found this article: https://web.dev/how-to-use-local-https/ Didn't try, but the title sounds promising ;)
